services:

  mongo:
    image: mongo
    volumes:
    - mongo_vol:/data/db
    ports:
    - 27017:27017

  backend:
    image: miguelfdas/backend_project_iacd:backend
    ports:
      - 80:80
    volumes:
    - backend_vol:/backend/logs
    depends_on:
      - 'mongo'

  frontend:
    image: miguelfdas/frontend_project_iacd:frontend
    ports:
      - 3000:3000
    stdin_open: true
    tty: true 

volumes:
  mongo_vol:
  backend_vol: